version: "3"
services:
  app:
    container_name: clean_hexa_app
    build: .
    ports:
      - "5011:5011"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - clean_hexa_network
    depends_on:
      - db-app

  db-app:
    container_name: clean_hexa_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=username_docker
      - POSTGRES_PASSWORD=password_docker
      - POSTGRES_DB=blog
      - POSTGRES_HOST=db-app
    ports:
      - "6432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - clean_hexa_network

volumes:
  api:
  database_postgres:

networks:
  clean_hexa_network:
    driver: bridge
